### ISSUE TITLE
CoreBase.constructor definition is incorrect

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-common#5]
# TypeScript
> ```ts
> constructor(name?: string);
> ```

https://github.com/os-js/osjs-common/blob/master/index.d.ts#L113

# ES
> ```js
> constructor(defaultConfiguration, configuration, options) {
> ```

https://github.com/os-js/osjs-common/blob/master/src/core.js#L49

**Comment by andersevenrud** [comment]
Looks like the generation failed and used inherited arguments. Fixed now in a new release.
